twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['Form/form.theme.html.twig']
    globals:
        images_directory: '/uploads/images/'

when@test:
    twig:
        strict_variables: true
