twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['Form/form.theme.html.twig']
    globals:
        images_directory: '%env(IMAGES_DIRECTORY)%'
        placeholder_image: '/assets/img/placeholder.png'

when@test:
    twig:
        strict_variables: true
